title: 3mpowr App
description: Practical tools and community for injured workers and persons with disabilities.
baseurl: ""
url: "https://empowrapp08162025.github.io/empowr-site.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
