title: 3mpowr App
description: Practical tools and community for injured workers and persons with disabilities.
baseurl: ""
url: "https://3mpwrapp.github.io"

# Theme and markdown
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks and timezone
permalink: pretty
timezone: UTC

# Kramdown options (for Table of Contents)
kramdown:
  toc_levels: 2..4

# SEO and social (jekyll-seo-tag)
author:
  name: "3mpowr App"
logo: /assets/favicon.svg

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og-image.png

social:
  name: "3mpowr App"
  links:
    - https://github.com/3mpowrApp
    - https://www.facebook.com/3mpowrapp
    - https://x.com/3mpowrApp0816
    - https://www.instagram.com/3mpowrapp/

ga_measurement_id: ""

twitter_username: "3mpowrApp0816"
github_username: "3mpowrApp"

# New: asset variables used by custom-head.html
favicon: /assets/favicon.svg
webmanifest: /assets/site.webmanifest
# apple_touch_icon: /assets/apple-touch-icon.png  # Uncomment after adding the file
