name: Accessibility (pa11y-ci)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * 1" # Weekly Monday 06:00 UTC

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no build needed; we test the deployed site)
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run pa11y-ci against production
        run: |
          npx pa11y-ci --config .pa11yci.json
