name: Link Checker (lychee)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * 1" # Weekly Monday 08:00 UTC

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --config lychee.toml
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
