name: Link Checker (lychee)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * 1" # Weekly Monday 08:00 UTC

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-mail
            --max-redirects 5
            --retry-wait-time 2
            --retry-count 2
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
